### PR TITLE
notOk() assert

### PR DESCRIPTION
**Pull request by piranna**
This document the [notOk()](https://github.com/jquery/qunit/pull/745) assert.]

### CODE REVIEW

**Comment by leobalter** [comment]
LGTM

**Comment by arthurvr** [comment]
Yup, LGTM! Thanks @piranna!

**Comment by piranna** [comment]
> Yup, LGTM! Thanks @piranna!

You are welcome :-)

**Comment by leobalter** [comment]
Waiting for the 1.18.0 release

**Comment by jzaefferer** [comment]
You can merge this into a `1-18` branch. We can use that to gather all updates for 1.18 instead of keeping PRs open.

**Comment by arthurvr** [comment]
> You can merge this into a 1-18 branch.

Is there a particular reason this PR is staying open or shall I go ahead and do that?

**Comment by jzaefferer** [comment]
By now 1.18 is out, so this should land in master and get published. I forgot about it when I did the release.

**Comment by arthurvr** [comment]
haha, makes sense. Landing now.

**Comment by jzaefferer** [comment]
Thanks. The tag should have been increased to 1.18.0 (minor, not patch). Not an actual problem, more for keeping track with actual QUnit changes.

**Comment by arthurvr** [comment]
Whoops! Sorry!

**Pull request closed without merging**
